// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX9Jkn9CikMg1bjhGysbJq-H6DwncWKtQ',
    appId: '1:583432580320:web:ed79b9dda2f6b629c9b485',
    messagingSenderId: '583432580320',
    projectId: 'student-a1550',
    authDomain: 'student-a1550.firebaseapp.com',
    storageBucket: 'student-a1550.firebasestorage.app',
    measurementId: 'G-N39PVTX85V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlTWKzPfHAIbBh2W9kVQ7-5cgcT4c8ZM',
    appId: '1:583432580320:android:2ed745c479c794e4c9b485',
    messagingSenderId: '583432580320',
    projectId: 'student-a1550',
    storageBucket: 'student-a1550.firebasestorage.app',
  );
}
